FIND_PATH(BENCHMARK_INCLUDE_DIR benchmark/benchmark.h 
    PATHS ENV C_INCLUDE_PATH
        ENV C_PLUS_INCLUDE_PATH
        ENV INCLUDE_PATH
)


FIND_LIBRARY(BENCHMARK_LIBRARY
  NAMES benchmark
  PATHS ENV LIBRARY_PATH #unix
        ENV LD_LIBRARY_PATH #unix
  )

IF (BENCHMARK_INCLUDE_DIR )
    SET(BENCHMARK_FOUND TRUE)
ENDIF(BENCHMARK_INCLUDE_DIR )

IF (BENCHMARK_FOUND AND BENCHMARK_LIBRARY)
	IF (NOT BENCHMARK_FIND_QUIETLY)
		MESSAGE(STATUS "Found BENCHMARK: ${BENCHMARK_INCLUDE_DIR}")
	ENDIF (NOT BENCHMARK_FIND_QUIETLY)
ELSE ()
	IF (BENCHMARK_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find BENCHMARK")
	ENDIF (BENCHMARK_FIND_REQUIRED)
ENDIF ()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BENCHMARK DEFAULT_MSG 
 BENCHMARK_INCLUDE_DIR BENCHMARK_LIBRARY)
